mysql:
  image: mysql:5.7
  container_name: bigquant-mysql-server-dev
  command:
    ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=bigquant
