egg-ts:
  build: .
  links:
    - mysql:bigquant-mysql-server
  ports:
    - '7000:7000'
  volumes:
    - ./volume:/app/volume
mysql:
  image: mysql:5.7
  container_name: bigquant-mysql-server
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=bigquant
